/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_hectorhernandez_12211096;

import java.awt.TextArea;
import javax.swing.JTextArea;

/**
 *
 * @author Hector
*/
public class BananaEats_Principal extends javax.swing.JFrame {

    

    /**
     * Creates new form BananaEats_Principal
     */
    public BananaEats_Principal() {
        initComponents();
        LlenarMatriz(text_area);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_banana_eats = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        bt_tarjeta_navidad = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_cargar = new javax.swing.JButton();
        bt_comenzar = new javax.swing.JButton();
        tf_instrucciones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_banana_eats.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        label_banana_eats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_banana_eats.setText("Banana Eats");
        jPanel1.add(label_banana_eats, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 21, 590, 33));

        text_area.setColumns(10);
        text_area.setRows(2);
        text_area.setTabSize(3);
        text_area.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(204, 0, 0)));
        text_area.setMaximumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(text_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 590, 410));

        bt_tarjeta_navidad.setBackground(new java.awt.Color(102, 255, 255));
        bt_tarjeta_navidad.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        bt_tarjeta_navidad.setText("Tarjeta Navideña");
        bt_tarjeta_navidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tarjeta_navidadMouseClicked(evt);
            }
        });
        jPanel1.add(bt_tarjeta_navidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 140, 40));

        bt_guardar.setBackground(new java.awt.Color(255, 255, 255));
        bt_guardar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt_guardar.setText("Guardar");
        jPanel1.add(bt_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 140, 50));

        bt_cargar.setBackground(new java.awt.Color(255, 255, 255));
        bt_cargar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt_cargar.setText("Cargar");
        jPanel1.add(bt_cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 150, 50));

        bt_comenzar.setBackground(new java.awt.Color(255, 255, 255));
        bt_comenzar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt_comenzar.setText("Comenzar");
        jPanel1.add(bt_comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 140, 50));

        tf_instrucciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf_instrucciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(tf_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 590, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_tarjeta_navidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tarjeta_navidadMouseClicked
        // TODO add your handling code here:
        Feliz_Navidad fn = new Feliz_Navidad();
        this.setVisible(false);
        fn.setVisible(true);
        
    }//GEN-LAST:event_bt_tarjeta_navidadMouseClicked
   
    public static void LlenarMatriz(JTextArea ta) {
        //Linea superior
        String s = "";
        for (int i = 0; i < 33; i++) {
            s += "*";
        }
        s += "\n";

        //centro de la forma
        for (int i = 0; i < 13; i++) {
            s += "*";
            for (int j = 0; j < 46; j++) {
                s += " ";
            }
            s += "*";
            s += "\n";
        }

        //Linea inferior
        for (int i = 0; i < 33; i++) {
            s += "*";
        }
        ta.setText(s);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BananaEats_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BananaEats_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BananaEats_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BananaEats_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BananaEats_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cargar;
    private javax.swing.JButton bt_comenzar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_tarjeta_navidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_banana_eats;
    private javax.swing.JTextArea text_area;
    private javax.swing.JTextField tf_instrucciones;
    // End of variables declaration//GEN-END:variables
    static String matriz[][] = new String[13][33];
    //static javax.swing.JTextArea textArea = new javax.swing.JTextArea();
}
